name: "LLM Code Reviewer"
description: "This GitHub Action automatically reviews PRs using multiple model."
author: 'tusgino'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository'
    required: true
  GEMINI_API_KEY:
    description: 'Google Gemini API key'
    required: false
  OPENAI_API_KEY:
    description: 'OpenAI API key'
    required: false
  GEMINI_MODEL:
    description: 'The Gemini model to use for code review'
    required: false
    default: 'gemini-1.5-flash-002'
  OPENAI_MODEL:
    description: 'The OpenAI model to use for code review'
    required: false
    default: 'gpt-4o-mini'
  INPUT_EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: ''
  HUMAN_LANGUAGE:
    description: 'The human language to use for code review'
    required: false
    default: 'en'
  PRIMARY_MODEL:
    description: 'The primary model to use for code review'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt

    - name: Install dependencies
      shell: bash
      run: |
          pip install -r requirements.txt

    - name: Run code review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        GEMINI_MODEL: ${{ inputs.GEMINI_MODEL }}
        OPENAI_MODEL: ${{ inputs.OPENAI_MODEL }}
        INPUT_EXCLUDE: ${{ inputs.INPUT_EXCLUDE }}
        HUMAN_LANGUAGE: ${{ inputs.HUMAN_LANGUAGE }}
        PRIMARY_MODEL: ${{ inputs.PRIMARY_MODEL }}
      run: python3.10 -m src.main ${{ github.action_path }}/src/main.py
