name: "LLM Code Reviewer"
description: "This GitHub Action automatically reviews PRs using multiple model."
author: 'tusgino'

branding:
  icon: 'eye'
  color: 'blue'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository'
    required: true
  GEMINI_API_KEY:
    description: 'Google Gemini API key'
    required: false
  OPENAI_API_KEY:
    description: 'OpenAI API key'
    required: false
  ANTHROPIC_API_KEY:
    description: 'Anthropic API key'
    required: false
  GEMINI_MODEL:
    description: 'The Gemini model to use for code review'
    required: false
    default: 'gemini-1.5-flash-002'
  OPENAI_MODEL:
    description: 'The OpenAI model to use for code review'
    required: false
    default: 'gpt-4o-mini'
  ANTHROPIC_MODEL:
    description: 'The Anthropic model to use for code review'
    required: false
  INPUT_EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: ''
  HUMAN_LANGUAGE:
    description: 'The human language to use for code review'
    required: false
    default: 'en'
  PRIMARY_MODEL:
    description: 'The primary model to use for code review'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f ${{ github.action_path }}/requirements.txt ]; then
          pip install -r ${{ github.action_path }}/requirements.txt
        else
          echo "Error: requirements.txt not found in ${{ github.action_path }}"
          exit 1
        fi

    - name: Run code review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ inputs.ANTHROPIC_API_KEY }}
        GEMINI_MODEL: ${{ inputs.GEMINI_MODEL }}
        OPENAI_MODEL: ${{ inputs.OPENAI_MODEL }}
        ANTHROPIC_MODEL: ${{ inputs.ANTHROPIC_MODEL }}
        INPUT_EXCLUDE: ${{ inputs.INPUT_EXCLUDE }}
        HUMAN_LANGUAGE: ${{ inputs.HUMAN_LANGUAGE }}
        PRIMARY_MODEL: ${{ inputs.PRIMARY_MODEL }}
      run: |
        if [ -f ${{ github.action_path }}/src/main.py ]; then
          python -m src.main ${{ github.action_path }}/src/main.py
        else
          echo "Error: main.py not found in ${{ github.action_path }}/src/"
          exit 1
        fi
