name: Gemini AI Code Reviewer
on:
  issue_comment:
    types: [created]
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/tool-review')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Cache pip packages
      uses: actions/cache@v4
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
      - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ "${{ steps.pip-cache.outputs.cache-hit }}" != 'true' ]; then
          pip install -r requirements.txt
        fi
          
      - name: Run LLM AI Code Reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ vars.GEMINI_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
          HUMAN_LANGUAGE: 'vi'
          PRIMARY_MODEL: 'openai'
        run: |
          python3.10 -m src.main src/main.py
