name: LLM AI Code Reviewer
on:
  issue_comment:
    types: [created]
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/tool-review')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
          
      - name: Install dependencies
        shell: bash
        run: |
            pip install -r requirements.txt
          
      - name: Run LLM AI Code Reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ vars.GEMINI_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_MODEL: ${{ vars.ANTHROPIC_MODEL }}
          HUMAN_LANGUAGE: ${{ vars.HUMAN_LANGUAGE }}
          PRIMARY_MODEL: ${{ vars.PRIMARY_MODEL }}
        run: |
          python3.10 -m src.main src/main.py
